### ISSUE TITLE
[Feature] User profile's onboard/offboard checklist section

### ISSUE THREAD

**Issue by GereltuyaMz** [nestsolutionsllc/nest-hr#33]
### User profile's onboard/offboard checklist

- [ ] Create To Read guide
- [ ] Create Onboarding checklist
- [ ] Create Offboarding checklist
- [ ] Depend on the department, the checklist fields would change

Reference 
1. [notion checklist](https://www.notion.so/nestacademy/7e17e5844bec412ea2dd9088099cbf7f?v=9d9820e8b81d4ca99b9c261bb2aced0d&p=c170cd2aa6f04321a8fe0a7301933f04&pm=s)
2. [the ultimate onboarding checklist](https://www.talentlyft.com/en/blog/article/183/the-ultimate-onboarding-checklist)
